faithlead_rest_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: FaithleadRestBundle:Default:index }

#faithlead_rest_user_all:
#    pattern:  /users
#    defaults: { _controller: FaithleadRestBundle:User:all, _format:~ }
#    requirements:
#        _method: GET
#
#faithlead_rest_user_create:
#    pattern:  /users
#    defaults: { _controller: FaithleadRestBundle:User:create, _format: json }
#    requirements:
#        _method: POST

user:
    type: rest
    resource: Faithlead\RestBundle\Controller\UserController

emailtemplate:
  type: rest
  resource: Faithlead\RestBundle\Controller\EmailTemplateController
emailhistory:
  type: rest
  resource: Faithlead\RestBundle\Controller\EmailHistoryController