user:
    type: rest
    resource: Faithlead\RestBundle\Controller\UserController

emailtemplate:
  type: rest
  resource: Faithlead\RestBundle\Controller\EmailTemplateController

emailsetting:
  type: rest
  resource: Faithlead\RestBundle\Controller\EmailSettingController

emailhistory:
  type: rest
  resource: Faithlead\RestBundle\Controller\EmailHistoryController

category:
  type: rest
  resource: Faithlead\RestBundle\Controller\CategoryController

companycategory:
  type: rest
  resource: Faithlead\RestBundle\Controller\CompanyCategoryController

order-info:
    type: rest
    resource: Faithlead\RestBundle\Controller\OrderInfoController

email-parser:
    path:      /email-parser/
    defaults:  { _controller: FaithleadRestBundle:EmailParser:index }