parameters:
#    faithlead_rest.example.class: Faithlead\RestBundle\Example

services:
#    faithlead_rest.example:
#        class: %faithlead_rest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
